import { Component } from '@angular/core';
import { EstadoCielo } from './temperatura/temperatura.component';
import { LoggerService } from './servicios/logger.servicio';

export interface Ciudad {
    nombre:string;
    codigo:string;
    tempMax:number;
    tempMin:number;
    cielo:  EstadoCielo;
}

@Component({
    selector: 'app-root',
    templateUrl: './app.component.html',
    styleUrls: ['./app.component.css']
})

export class AppComponent {
    title = 'Temperaturas por Provincia';


    ciudades:Ciudad[] = [
        {
            nombre:"Álava",
            codigo:"01059",
            tempMax:0,
            tempMin:0,
            cielo:EstadoCielo.Soleado
        },
        {
            nombre:"Albacete",
            codigo:"02003",
            tempMax:0,
            tempMin:0,
            cielo:EstadoCielo.Soleado
        },
        {
            nombre:"Alicante",
            codigo:"03014",
            tempMax:0,
            tempMin:0,
            cielo:EstadoCielo.Soleado
        },
        {
            nombre:"Almería",
            codigo:"04013",
            tempMax:0,
            tempMin:0,
            cielo:EstadoCielo.Soleado
        },
        {
            nombre:"Ávila",
            codigo:"05019",
            tempMax:0,
            tempMin:0,
            cielo:EstadoCielo.Soleado
        },
        {
            nombre:"Badajoz",
            codigo:"06015",
            tempMax:0,
            tempMin:0,
            cielo:EstadoCielo.Soleado
        },
        {
            nombre:"Baleares",
            codigo:"07040",
            tempMax:0,
            tempMin:0,
            cielo:EstadoCielo.Soleado
        },
        {
            nombre:"Barcelona",
            codigo:"08019",
            tempMax:0,
            tempMin:0,
            cielo:EstadoCielo.Soleado
        },
        {
            nombre:"Burgos",
            codigo:"09059",
            tempMax:0,
            tempMin:0,
            cielo:EstadoCielo.Soleado
        },
        {
            nombre:"Cáceres",
            codigo:"10037",
            tempMax:0,
            tempMin:0,
            cielo:EstadoCielo.Soleado
        },
        {
            nombre:"Cádiz",
            codigo:"11012",
            tempMax:0,
            tempMin:0,
            cielo:EstadoCielo.Soleado
        },
        {
            nombre:"Castellón",
            codigo:"12040",
            tempMax:0,
            tempMin:0,
            cielo:EstadoCielo.Soleado
        },
        {
            nombre:"Ciudad Real",
            codigo:"13034",
            tempMax:0,
            tempMin:0,
            cielo:EstadoCielo.Soleado
        },
        {
            nombre:"Córdoba",
            codigo:"14021",
            tempMax:0,
            tempMin:0,
            cielo:EstadoCielo.Soleado
        },
        {
            nombre:"Coruña",
            codigo:"15030",
            tempMax:0,
            tempMin:0,
            cielo:EstadoCielo.Soleado
        },
        {
            nombre:"Cuenca",
            codigo:"16078",
            tempMax:0,
            tempMin:0,
            cielo:EstadoCielo.Soleado
        },
        {
            nombre:"Gerona",
            codigo:"17079",
            tempMax:0,
            tempMin:0,
            cielo:EstadoCielo.Soleado
        },
        {
            nombre:"Granada",
            codigo:"18087",
            tempMax:0,
            tempMin:0,
            cielo:EstadoCielo.Soleado
        },
        {
            nombre:"Guadalajara",
            codigo:"19130",
            tempMax:0,
            tempMin:0,
            cielo:EstadoCielo.Soleado
        },
        {
            nombre:"Guipúzcoa",
            codigo:"20069",
            tempMax:0,
            tempMin:0,
            cielo:EstadoCielo.Soleado
        },
        {
            nombre:"Huelva",
            codigo:"21041",
            tempMax:0,
            tempMin:0,
            cielo:EstadoCielo.Soleado
        },
        {
            nombre:"Huesca",
            codigo:"22125",
            tempMax:0,
            tempMin:0,
            cielo:EstadoCielo.Soleado
        },
        {
            nombre:"Jaén",
            codigo:"23050",
            tempMax:0,
            tempMin:0,
            cielo:EstadoCielo.Soleado
        },
        {
            nombre:"León",
            codigo:"24089",
            tempMax:0,
            tempMin:0,
            cielo:EstadoCielo.Soleado
        },
        {
            nombre:"Lérida",
            codigo:"25120",
            tempMax:0,
            tempMin:0,
            cielo:EstadoCielo.Soleado
        },
        {
            nombre:"La Rioja",
            codigo:"26089",
            tempMax:0,
            tempMin:0,
            cielo:EstadoCielo.Soleado
        },
        {
            nombre:"Lugo",
            codigo:"27028",
            tempMax:0,
            tempMin:0,
            cielo:EstadoCielo.Soleado
        },
        {
            nombre:"Madrid",
            codigo:"28079",
            tempMax:0,
            tempMin:0,
            cielo:EstadoCielo.Soleado
        },
        {
            nombre:"Málaga",
            codigo:"29067",
            tempMax:0,
            tempMin:0,
            cielo:EstadoCielo.Soleado
        },
        {
            nombre:"Murcia",
            codigo:"30030",
            tempMax:0,
            tempMin:0,
            cielo:EstadoCielo.Soleado
        },
        {
            nombre:"Navarra",
            codigo:"31201",
            tempMax:0,
            tempMin:0,
            cielo:EstadoCielo.Soleado
        },
        {
            nombre:"Orense",
            codigo:"32054",
            tempMax:0,
            tempMin:0,
            cielo:EstadoCielo.Soleado
        },
        {
            nombre:"Oviedo",
            codigo:"33044",
            tempMax:0,
            tempMin:0,
            cielo:EstadoCielo.Soleado
        },
        {
            nombre:"Palencia",
            codigo:"34120",
            tempMax:0,
            tempMin:0,
            cielo:EstadoCielo.Soleado
        },
        {
            nombre:"Las Palmas",
            codigo:"35016",
            tempMax:0,
            tempMin:0,
            cielo:EstadoCielo.Soleado
        },
        {
            nombre:"Pontevedra",
            codigo:"36038",
            tempMax:0,
            tempMin:0,
            cielo:EstadoCielo.Soleado
        },
        {
            nombre:"Salamanca",
            codigo:"37274",
            tempMax:0,
            tempMin:0,
            cielo:EstadoCielo.Soleado
        },
        {
            nombre:"Santa Cruz de Tenerife",
            codigo:"38038",
            tempMax:0,
            tempMin:0,
            cielo:EstadoCielo.Soleado
        },
        {
            nombre:"Santander",
            codigo:"39075",
            tempMax:0,
            tempMin:0,
            cielo:EstadoCielo.Soleado
        },
        {
            nombre:"Segovia",
            codigo:"40194",
            tempMax:0,
            tempMin:0,
            cielo:EstadoCielo.Soleado
        },
        {
            nombre:"Sevilla",
            codigo:"41091",
            tempMax:0,
            tempMin:0,
            cielo:EstadoCielo.Soleado
        },
        {
            nombre:"Soria",
            codigo:"42173",
            tempMax:0,
            tempMin:0,
            cielo:EstadoCielo.Soleado
        },
        {
            nombre:"Tarragona",
            codigo:"43148",
            tempMax:0,
            tempMin:0,
            cielo:EstadoCielo.Soleado
        },
        {
            nombre:"Teruel",
            codigo:"44216",
            tempMax:0,
            tempMin:0,
            cielo:EstadoCielo.Soleado
        },
        {
            nombre:"Toledo",
            codigo:"45168",
            tempMax:0,
            tempMin:0,
            cielo:EstadoCielo.Soleado
        },
        {
            nombre:"Valencia",
            codigo:"46250",
            tempMax:0,
            tempMin:0,
            cielo:EstadoCielo.Soleado
        },
        {
            nombre:"Valladolid",
            codigo:"47186",
            tempMax:0,
            tempMin:0,
            cielo:EstadoCielo.Soleado
        },
        {
            nombre:"Vizcaya",
            codigo:"48020",
            tempMax:0,
            tempMin:0,
            cielo:EstadoCielo.Soleado
        },
        {
            nombre:"Zamora",
            codigo:"49275",
            tempMax:0,
            tempMin:0,
            cielo:EstadoCielo.Soleado
        },
        {
            nombre:"Zaragoza",
            codigo:"50297",
            tempMax:0,
            tempMin:0,
            cielo:EstadoCielo.Soleado
        },
        {
            nombre:"Ceuta",
            codigo:"51001",
            tempMax:0,
            tempMin:0,
            cielo:EstadoCielo.Soleado
        },
        {
            nombre:"Melilla",
            codigo:"52001",
            tempMax:0,
            tempMin:0,
            cielo:EstadoCielo.Soleado
        }
    ];

    
    filtro = "";

    /* Clase para sacar mensajes por consola */
    constructor (private log: LoggerService){}

    fecha = new Date();

    cambioTemperatura(event:number):void{
        this.log.log("Nueva temperatura: " + event);
    }
}
